USE [master]
GO

/****** Object:  Database [BaseCrm]    Script Date: 22/12/2025 16:19:34 ******/
CREATE DATABASE [BaseCrm]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BaseCrm_Data', FILENAME = N'G:\MSSQL2017\MSSQL14.SQLEXPRESS\MSSQL\DATA\BaseCrm.mdf' , SIZE = 332544KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'BaseCRM_Log', FILENAME = N'G:\MSSQL2017\MSSQL14.SQLEXPRESS\MSSQL\DATA\BaseCrm_log.LDF' , SIZE = 768KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BaseCrm].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [BaseCrm] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BaseCrm] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BaseCrm] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BaseCrm] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BaseCrm] SET ARITHABORT OFF 
GO

ALTER DATABASE [BaseCrm] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BaseCrm] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [BaseCrm] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BaseCrm] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BaseCrm] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BaseCrm] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BaseCrm] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BaseCrm] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BaseCrm] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BaseCrm] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BaseCrm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BaseCrm] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BaseCrm] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BaseCrm] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BaseCrm] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BaseCrm] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BaseCrm] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BaseCrm] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BaseCrm] SET  MULTI_USER 
GO

ALTER DATABASE [BaseCrm] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [BaseCrm] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BaseCrm] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BaseCrm] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BaseCrm] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BaseCrm] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BaseCrm] SET  READ_WRITE 
GO

